declare module 'formidable-serverless'
declare module 'codemirror/mode/python/python'
declare module 'codemirror/mode/clike/clike'
declare module 'codemirror/lib/codemirror'
declare module 'codemirror/theme/material.css'
declare module 'codemirror/mode/javascript/javascript'
