import type { NextPage } from 'next'
import Button from '../components/Button'
import Head from 'next/head'
import Image from 'next/image'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import Layout from '../components/Layout'
import styles from '../styles/Home.module.css'
import { faSearch } from '@fortawesome/free-solid-svg-icons'
import Wave from '../components/Wave'
// TODO implement debouncing for searches
const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Algo Share: HomePage</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				<Wave />
				<form className="flex flex-col relative top-1/2 transform left-1/2 -translate-x-1/2 -translate-y-1/2 gap-2 items-center">
					<div className="flex flex-row">
						<label>
							<input
								type="text"
								placeholder="Algorithm"
								className="min-h-full rounded-l-md px-2 py-1"
							/>
						</label>
						<label>
							<select
								name="language"
								id="language"
								className="h-full rounded-r-md border-l-2"
							>
								<option value="CSS">css</option>
							</select>
						</label>
					</div>
					<Button text="Search">
						<FontAwesomeIcon icon={faSearch} size={'sm'} />
					</Button>
				</form>
			</Layout>
		</div>
	)
}

export default Home
